/*
 Karen Roldán 0901-17-63
busca a un empleado en la base de datos
 */
package laboratorio2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Karen
 */
public class Buscar extends javax.swing.JFrame {

    /**
     * Creates new form Buscar
     */
    public Buscar() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        T_buscar = new javax.swing.JTextField();
        B_buscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        L_codigo_emple = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        L_nombre_emple = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        L_sueldo_emple = new javax.swing.JLabel();
        L_departamento_emple = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        B_cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Buscar Empleado:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 130, 31));

        T_buscar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel2.add(T_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 169, 30));

        B_buscar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        B_buscar.setText("Buscar");
        B_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_buscarActionPerformed(evt);
            }
        });
        jPanel2.add(B_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("DPI");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 55, -1));

        L_codigo_emple.setBackground(new java.awt.Color(204, 204, 255));
        L_codigo_emple.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        L_codigo_emple.setOpaque(true);
        jPanel2.add(L_codigo_emple, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 132, 28));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Nombre");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        L_nombre_emple.setBackground(new java.awt.Color(204, 204, 255));
        L_nombre_emple.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        L_nombre_emple.setOpaque(true);
        jPanel2.add(L_nombre_emple, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 132, 29));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Sueldo");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 55, -1));

        L_sueldo_emple.setBackground(new java.awt.Color(204, 204, 255));
        L_sueldo_emple.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        L_sueldo_emple.setOpaque(true);
        jPanel2.add(L_sueldo_emple, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 197, 132, 30));

        L_departamento_emple.setBackground(new java.awt.Color(204, 204, 255));
        L_departamento_emple.setOpaque(true);
        jPanel2.add(L_departamento_emple, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 132, 28));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Departamento");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 114, -1));

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 323, 100, 30));

        B_cerrar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        B_cerrar.setText("Cerrar");
        B_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_cerrarActionPerformed(evt);
            }
        });
        jPanel2.add(B_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 323, 100, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   // busca a un empleado en la base de datos y los coloca en los lugares indicados 
    void buscar_empleado(String nombre) throws SQLException
    {
        PreparedStatement ps= null;
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/base_datos", "root", "");
        String sql =" SELECT * FROM empleado_nomina WHERE nombre_empleado = '"+nombre+"'";
        try
        {
          Statement st= con.createStatement();
          ResultSet rs = st.executeQuery(sql);
          if(rs.next()){
                L_codigo_emple.setText(rs.getString("codigo_empleado"));
                L_nombre_emple.setText(rs.getString("nombre_empleado"));
                L_sueldo_emple.setText(rs.getString("sueldo_empleado"));
                L_departamento_emple.setText(rs.getString("codigo_departamento"));
            } else {
                JOptionPane.showMessageDialog(null, "Alumno no registrado.");
            }
        }
        catch (Exception e){
            
        }
    }
     // boton que ejecuta buscar
    private void B_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_buscarActionPerformed
        // Busca datos en la base de datos con el nombre
     String nombre= T_buscar.getText();
     
        try {
            buscar_empleado(nombre);
        } catch (SQLException ex) {
            Logger.getLogger(Buscar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_B_buscarActionPerformed
    // boton que regresa al menu inicial
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        menu  regresar=new menu();
        regresar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void B_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_cerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_buscar;
    private javax.swing.JButton B_cerrar;
    private javax.swing.JLabel L_codigo_emple;
    private javax.swing.JLabel L_departamento_emple;
    private javax.swing.JLabel L_nombre_emple;
    private javax.swing.JLabel L_sueldo_emple;
    private javax.swing.JTextField T_buscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
