/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laboratorio2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Karen
 */
public class empleados extends javax.swing.JFrame {

    /**
     * Creates new form empleados
     */
    String Str_puesto_CB;
    String Str_departamento_CB;
    String Str_codigo_puesto;
    
    public empleados() {
        initComponents();
        mostrarpuesto();
        mostrardepartamento();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        T_nombre_empleado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        T_sueldo_empleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CB_puesto = new javax.swing.JComboBox<>();
        CB_departamento = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        T_dpi_empleado = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        L_mostrar = new javax.swing.JLabel();
        B_regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel1.setText("Registro de Empleado");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 199, 34));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Nombre: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 130, 97, 25));

        T_nombre_empleado.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(T_nombre_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 230, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Suldo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 166, 97, 27));

        T_sueldo_empleado.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(T_sueldo_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 230, 27));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Puesto:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 110, -1));

        CB_puesto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(CB_puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 210, 230, -1));

        CB_departamento.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(CB_departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 230, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Departamento:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 110, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("DPI");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 100, -1, -1));

        T_dpi_empleado.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(T_dpi_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 230, -1));

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton1.setText("Registrar Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 315, 140, -1));

        L_mostrar.setBackground(new java.awt.Color(204, 204, 255));
        L_mostrar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        L_mostrar.setOpaque(true);
        jPanel1.add(L_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 179, 27));

        B_regresar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        B_regresar.setText("Regresar");
        B_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_regresarActionPerformed(evt);
            }
        });
        jPanel1.add(B_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        guardardatos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void B_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_regresarActionPerformed
        menu  regresar=new menu();
        regresar.setVisible(true);
         dispose();
    }//GEN-LAST:event_B_regresarActionPerformed

    public void guardardatos()
    {
        
          try{            
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_datos", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into empleado_nomina(codigo_empleado,nombre_empleado,sueldo_empleado,codigo_puesto,codigo_departamento) values(?,?,?,?,?)");
            Str_puesto_CB= CB_puesto.getSelectedItem().toString();
            Str_departamento_CB= CB_departamento.getSelectedItem().toString();
            
            pst.setString(1, T_dpi_empleado.getText().trim());
            pst.setString(2, T_nombre_empleado.getText().trim());
            pst.setString(3, T_sueldo_empleado.getText().trim());
            pst.setString(4, Str_puesto_CB);
            pst.setString(5, Str_departamento_CB);
            pst.executeUpdate();
        
            L_mostrar.setText("Registro exitoso");
            
        }catch (Exception e){
            System.out.println("Error "+e);
        }
    }
  
      
    public void mostrarpuesto()
    {
        try{
            Connection con=null;
            Class.forName("com.mysql.jdbc.Driver");
            con =DriverManager.getConnection("jdbc:mysql://localhost/base_datos", "root", "");

            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from puesto");
            CB_puesto.addItem("Seleccione puesto");
                 while(rs.next())
                  {
                      this.CB_puesto.addItem(rs.getString("codigo_puesto"));
                  }
              }catch (Exception e){
                  System.out.println("Error "+e);
              }
    }
    
     public void mostrardepartamento()
    {
        try{
            Connection con=null;
            Class.forName("com.mysql.jdbc.Driver");
            con =DriverManager.getConnection("jdbc:mysql://localhost/base_datos", "root", "");

            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from departamento");
                CB_departamento.addItem("Seleccione departamento");
                 while(rs.next())
                  {
                      this.CB_departamento.addItem(rs.getString("codigo_departamento"));
                  }
              }catch (Exception e){
                  System.out.println("Error "+e);
              }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_regresar;
    private javax.swing.JComboBox<String> CB_departamento;
    private javax.swing.JComboBox<String> CB_puesto;
    private javax.swing.JLabel L_mostrar;
    private javax.swing.JTextField T_dpi_empleado;
    private javax.swing.JTextField T_nombre_empleado;
    private javax.swing.JTextField T_sueldo_empleado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
