/*
Karen Roldan 0901-17-63

ingresa los conceptos como igss, isr etc 
 */
package laboratorio2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

/**
 *
 * @author Karen
 */
public class mantenimiento_concepto extends javax.swing.JFrame {

    /**
     * Creates new form mantenimiento_concepto
     */
    public mantenimiento_concepto() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        T_codigo_concepto = new javax.swing.JTextField();
        T_nombre_concepto = new javax.swing.JTextField();
        CB_efecto_concepto = new javax.swing.JComboBox<>();
        B_registrar_concepto = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        L_mostrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Conceptos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 83, 31));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Codigo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 90, 26));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 100, 20));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Efecto:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 90, -1));

        T_codigo_concepto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(T_codigo_concepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 141, 30));

        T_nombre_concepto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(T_nombre_concepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 141, -1));

        CB_efecto_concepto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        CB_efecto_concepto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma", "Resta" }));
        jPanel1.add(CB_efecto_concepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 141, -1));

        B_registrar_concepto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        B_registrar_concepto.setText("Registrar Concepto");
        B_registrar_concepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_registrar_conceptoActionPerformed(evt);
            }
        });
        jPanel1.add(B_registrar_concepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 170, -1));

        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 100, -1));

        L_mostrar.setBackground(new java.awt.Color(204, 204, 255));
        L_mostrar.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        L_mostrar.setOpaque(true);
        jPanel1.add(L_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // guarda los datos ingresador en la base de datos
    public void guardarconcepto()
    {
        
          try{ 
            String Str_CB_concepto;
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/base_datos", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into concepto_nomina(codigo_concepto,nombre_concepto,efecto_concepto) values(?,?,?)");
            Str_CB_concepto= CB_efecto_concepto.getSelectedItem().toString();
            
            pst.setString(1, T_codigo_concepto.getText().trim());
            pst.setString(2, T_nombre_concepto.getText().trim());
            pst.setString(3, Str_CB_concepto);
            pst.executeUpdate();
        
            L_mostrar.setText("Registro exitoso");
            
        }catch (Exception e){
            System.out.println("Error "+e);
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         menu  regresar=new menu();
        regresar.setVisible(true);
         dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void B_registrar_conceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_registrar_conceptoActionPerformed
        // permite registrar en la base de datos los conceptos
        guardarconcepto();
        
    }//GEN-LAST:event_B_registrar_conceptoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mantenimiento_concepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mantenimiento_concepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mantenimiento_concepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mantenimiento_concepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mantenimiento_concepto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_registrar_concepto;
    private javax.swing.JComboBox<String> CB_efecto_concepto;
    private javax.swing.JLabel L_mostrar;
    private javax.swing.JTextField T_codigo_concepto;
    private javax.swing.JTextField T_nombre_concepto;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
