/*
 Karen Roldan 0901-17-63
    permite el ingreso de los usuarios o administradores
 */
package laboratorio2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class usuarios extends javax.swing.JFrame {

    /**
     * Creates new form usuarios
     */
    public usuarios() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        T_usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Butt_aceptar = new javax.swing.JButton();
        Butt_cancelar = new javax.swing.JButton();
        T_contraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel1.setText("Usuario:");

        T_usuario.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel2.setText("Contraseña: ");

        Butt_aceptar.setBackground(new java.awt.Color(204, 204, 255));
        Butt_aceptar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Butt_aceptar.setText("Aceptar");
        Butt_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt_aceptarActionPerformed(evt);
            }
        });

        Butt_cancelar.setBackground(new java.awt.Color(204, 204, 255));
        Butt_cancelar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Butt_cancelar.setText("Cancelar");
        Butt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Butt_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(Butt_aceptar)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(T_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(T_contraseña)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(Butt_cancelar)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(T_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(T_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Butt_aceptar)
                    .addComponent(Butt_cancelar))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // permite verificar si es un administrador o usuario
    void login(String usuario, String pass) throws SQLException
    {
        
        String cap="";
        PreparedStatement ps= null;
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/base_datos", "root", "");
        String sql =" SELECT * FROM usuario_nomina WHERE nombre_usuario = '"+usuario+"'&& clave_usuario='"+pass+"'";
        
        try
        {
           // verifica   
            
          Statement st= con.createStatement();
          ResultSet rs = st.executeQuery(sql);
          //verifica si el usuario ingresado en la base de datos coincide con la ingresada en el textfield
          
          while(rs.next())
          {
            cap=rs.getString("estado_usuario");  
          }
          //verifica si es un administrador mostrara un menu
          if(cap.equals("Administrador"))
          {
              this.setVisible(false);
              JOptionPane.showMessageDialog(null,"Bienvenido Administrador");
              menu ingreso = new menu();
              ingreso.setVisible(true);
              ingreso.pack();  
          }
          // verifica si es un usuario y desplegara solo la planilla
           if(cap.equals("Usuario"))
          {
              this.setVisible(false);
              JOptionPane.showMessageDialog(null,"Bienvenido Usuario");
              Planillas_Usuario ingreso = new Planillas_Usuario();
              ingreso.setVisible(true);
              ingreso.pack();  
          }
           if((!cap.equals("Administrador")) && (!cap.equals("Usuario")))
           {
               JOptionPane.showMessageDialog(null,"Usuario no registrado");
           }
        }
        catch (Exception e){
                  System.out.println("Error "+e);
              } 
    }
    
    //boton que verifica el ingreso del usuario
    private void Butt_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butt_aceptarActionPerformed
        String usuario=T_usuario.getText();
        String pass= new String(T_contraseña.getPassword());
        
        try {
            login(usuario,pass);
        } catch (SQLException ex) {
            Logger.getLogger(usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_Butt_aceptarActionPerformed

    private void Butt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Butt_cancelarActionPerformed
         System.exit(WIDTH); 
    }//GEN-LAST:event_Butt_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Butt_aceptar;
    private javax.swing.JButton Butt_cancelar;
    private javax.swing.JPasswordField T_contraseña;
    private javax.swing.JTextField T_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
